import tcowatchdog


def lambda_handler(event):
    tcosetter = tcowatchdog.TcoWatchDog()
    tcosetter.settco(event)


event = "{'resource': '/testing', 'path': '/testing', 'httpMethod': 'POST', 'headers': {'Accept': 'application/json, text/plain, */*', 'Content-Type': 'application/json', 'Host': 'igdlr449lh.execute-api.us-east-1.amazonaws.com', 'User-Agent': 'axios/0.21.1', 'X-Amzn-Trace-Id': 'Root=1-619fc078-31ffbf0c7054eb32742a828c', 'x-api-key': 'CHOZ2xjpjh8TBibLf8K0rai6O9uUoPcacydKHobg', 'X-Forwarded-For': '54.194.244.111', 'X-Forwarded-Port': '443', 'X-Forwarded-Proto': 'https'}, 'multiValueHeaders': {'Accept': ['application/json, text/plain, */*'], 'Content-Type': ['application/json'], 'Host': ['igdlr449lh.execute-api.us-east-1.amazonaws.com'], 'User-Agent': ['axios/0.21.1'], 'X-Amzn-Trace-Id': ['Root=1-619fc078-31ffbf0c7054eb32742a828c'], 'x-api-key': ['CHOZ2xjpjh8TBibLf8K0rai6O9uUoPcacydKHobg'], 'X-Forwarded-For': ['54.194.244.111'], 'X-Forwarded-Port': ['443'], 'X-Forwarded-Proto': ['https']}, 'queryStringParameters': None, 'multiValueQueryStringParameters': None, 'pathParameters': None, 'stageVariables': None, 'requestContext': {'resourceId': 'nps8r5', 'resourcePath': '/testing', 'httpMethod': 'POST', 'extendedRequestId': 'JXsC0FUXIAMFT_Q=', 'requestTime': '25/Nov/2021:16:57:28 +0000', 'path': '/default/testing', 'accountId': '771039649440', 'protocol': 'HTTP/1.1', 'stage': 'default', 'domainPrefix': 'igdlr449lh', 'requestTimeEpoch': 1637859448211, 'requestId': 'c7e51214-32f4-48d1-bdbf-daa4f018b64b', 'identity': {'cognitoIdentityPoolId': None, 'cognitoIdentityId': None, 'apiKey': 'CHOZ2xjpjh8TBibLf8K0rai6O9uUoPcacydKHobg', 'principalOrgId': None, 'cognitoAuthenticationType': None, 'userArn': None, 'apiKeyId': 'pksabr5yp5', 'userAgent': 'axios/0.21.1', 'accountId': None, 'caller': None, 'sourceIp': '54.194.244.111', 'accessKey': None, 'cognitoAuthenticationProvider': None, 'user': None}, 'domainName': 'igdlr449lh.execute-api.us-east-1.amazonaws.com', 'apiId': 'igdlr449lh'}, 'body': '[{\"appname\":[\"app1\"],\"subsystem\":[],\"tcolevel\":\"low\"},{\"appname\":[\"app1\"],\"subsystem\":[\"sub1\"],\"tcolevel\":\"medium\"},{\"appname\":[\"app2\"],\"subsystem\":[\"sub2\",\"sub3\",\"sub4\"],\"tcolevel\":\"low\"},{\"appname\":[\"app3\",\"app4\"],\"subsystem\":[],\"tcolevel\":\"low\"}]', 'isBase64Encoded': False}"
tcowatchdog.TcoWatchDog().settco(event)