AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  TCO Watchdog App.
  An app to catch hooks from coralogix notifying the the account is at 90% capacity. 
  the app will reduce the tco policies to the lowests level.
  At 00:00UTC 

Globals:
  Function:
    Timeout: 900
    MemorySize: 1024
Resources:
  IngestLogs:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: tco_watchdog_lambda_app/
      Handler: app.lambda_handler
      Runtime: python3.8
      Role: <your lambda function execution arn string>
      ReservedConcurrentExecutions: 1
      Environment:
        Variables:
          PRIVATE_KEY: <your coralogix token goes here>
          APPLICATION_NAME: <your coralogx application name here>
          SUBSYSTEM_NAME: <your coralogx subsystem name here>
          TCO_KEY: <the api key for tco api>
          AWS_BUCKET_NAME: <The Bucket in which we store the state files in>