AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Dynamic TCO App.
  An app to catch hooks from coralogix notifying the the account is at 90% capacity. 
  the app will reduce the tco policies to the lowests level.
  At 00:00UTC 

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
Resources:
  DynamicTco:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./
      Handler: app.lambda_handler
      Runtime: python3.9
      Role: <your lambda function execution arn string>
      ReservedConcurrentExecutions: 1
      Environment:
        Variables:
          PRIVATE_KEY: <your coralogix token goes here>
          APPLICATION_NAME: <your coralogx application name here>
          SUBSYSTEM_NAME: <your coralogx subsystem name here>
          TCO_KEY: <the api key for tco api>
          AWS_BUCKET_NAME: <The Bucket in which we store the state files in>
      Events:
        HttpPost: #More info and code examples found at: https://docs.aws.amazon.com/lambda/latest/dg/services-apigateway-code.html#services-apigateway-code-python
          Type: Api
          Properties:
            Path: '/dynamictco_listener'
            Method: post